# Generated by Django 3.2.4 on 2021-07-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_comentarioscontacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.RenameModel(
            old_name='ComentariosContacto',
            new_name='ComentarioContacto',
        ),
    ]
