# Generated by Django 3.2.4 on 2021-08-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20210729_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12, verbose_name='Mat')),
                ('nombre', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumno Registro',
                'verbose_name_plural': 'Alumnos Registros',
                'ordering': ['-created'],
            },
        ),
    ]
