# Generated by Django 3.2.4 on 2021-08-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_alumnoregistro_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoregistro',
            name='imagen',
        ),
    ]
