# Generated by Django 3.2.4 on 2021-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_alumnoregistro1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnoregistro1',
            options={'ordering': ['-created'], 'verbose_name': 'Alumno Registros', 'verbose_name_plural': 'Alumnos Registros'},
        ),
        migrations.AlterField(
            model_name='alumnoregistro1',
            name='matricula',
            field=models.TextField(verbose_name='Mat'),
        ),
    ]
