# Generated by Django 3.2.4 on 2021-08-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_auto_20210802_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumnoRegistro1',
        ),
        migrations.AlterField(
            model_name='alumnoregistro',
            name='matricula',
            field=models.TextField(verbose_name='Usuario'),
        ),
    ]
