# Generated by Django 3.2.4 on 2021-08-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_auto_20210802_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoregistro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia'),
        ),
        migrations.AlterField(
            model_name='alumnoregistro',
            name='matricula',
            field=models.TextField(verbose_name='Matricula'),
        ),
    ]
