# Generated by Django 3.2.4 on 2021-08-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_auto_20210802_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoregistro',
            name='imagen',
        ),
    ]
